// my-vue-project-3/src/components/Menu.vue
<template>
  <div>
    <h2>Hello, {{settings.name}}</h2>
    <router-link to="/home">Home</router-link> |
    <router-link to="/about">About</router-link> |
    <router-link to="/settings">Settings</router-link> |
  </div>
</template>
<script>
import { mapState } from "vuex";
export default {
  name:"my-menu",
  computed:mapState(["settings"])
}
</script>

// my-react-project-3/src/components/Menu.jsx
import React, { Component } from "react";

import { Link } from "react-router-dom";

import { connect } from "react-redux";

class Menu extends Component {
  render() {
    return (
      <div>
        <h2>Hello, {this.props.settings.name}</h2> |
        <Link to={"/home"}>Home</Link> |
        <Link to={"/about"}>About</Link> |
        <Link to={"/settings"}>Settings</Link>
      </div>
    );
  }
}

const mapState = state => ({ settings: state.settings });

export default connect(mapState)(Menu);
